### ISSUE TITLE
[React] Images not loading until screen resize.

### ISSUE THREAD

**Issue by awitherow** [imgix/imgix.js#87]
Hello imgix.js

With React, I am using imgix to display a background photo in this way

```javascript
<div
  className="photo imgix-fluid"
  data-src={"https:" + image + "?auto=format&fit=clamp&crop=entropy"}
  />
```

with the class

```css
.photo {
  background-position: 50% 50%;
  background-size: cover;
} 
```

The page loads fully, but without the images. The images then load when I resize the viewport by 1px+.

I believe this is due to conflicts between the virtual DOM of React & imgix writing to the DOM.

Any ideas?
